const {test}=require('node:test');
const assert=require('node:assert/strict');
const {TunnelController,routeNotes}=require('./tunnels.cjs');
function setup(fail=false){const profiles=[{id:'a',name:'A',active:false,allowedIPs:'10.0.0.0/24'},{id:'b',name:'B',active:false,allowedIPs:'192.168.0.0/24'}];const commands=[];const controller=new TunnelController({list:async()=>profiles.map(p=>({...p})),log:()=>{},execute:async(p,action)=>{commands.push([p.id,action]);if(fail&&p.id==='a')throw Error('Failed');profiles.find(x=>x.id===p.id).active=action==='up'}});return {profiles,commands,controller}}
test('two connections remain active; disconnecting one preserves the other',async()=>{const {profiles,commands,controller}=setup();await Promise.all([controller.setActive('a',true),controller.setActive('b',true)]);assert.ok(profiles.every(p=>p.active));await controller.setActive('a',false);assert.equal(profiles[1].active,true);assert.deepEqual(commands,[['a','up'],['b','up'],['a','down']])});
test('failed connection does not block queued tunnel',async()=>{const {controller,profiles}=setup(true);const result=await Promise.allSettled([controller.setActive('a',true),controller.setActive('b',true)]);assert.equal(result[0].status,'rejected');assert.equal(profiles[1].active,true);assert.equal(controller.pending.size,0)});
test('rejects duplicate pending request; desired state is idempotent',async()=>{const {controller,commands}=setup();const first=controller.setActive('a',true);await assert.rejects(controller.setActive('a',true));await first;await controller.setActive('a',true);assert.equal(commands.length,1)});
test('reports overlapping IPv4, IPv6 and shared DNS but permits split/full routing',()=>{const profile={id:'a',allowedIPs:'10.0.0.0/24, fd00::/64',dns:'1.1.1.1'};assert.equal(routeNotes(profile,[{id:'b',name:'B',active:true,allowedIPs:'0.0.0.0/0',dns:'9.9.9.9'}]).length,2);assert.equal(routeNotes(profile,[{id:'b',name:'B',active:true,allowedIPs:'fd00::1/128'}]).length,1);assert.equal(routeNotes(profile,[{id:'b',active:true,allowedIPs:'192.168.0.0/24, fe80::/64'}]).length,0)});
test('unknown state never short-circuits a requested system check',async()=>{const calls=[];const controller=new TunnelController({list:async()=>[{id:'a',name:'A',active:false,statusUnknown:true}],log:()=>{},execute:async(p,action)=>calls.push(action)});await controller.setActive('a',false);assert.deepEqual(calls,['down'])});
